#ifndef INCLUDES_H
#define INCLUDES_H
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <iostream>
#include <stdint.h>
#include <string>
#include <math.h>
#include <unordered_map>
#include <array>
#include <vector>
#include <algorithm>
#include <fstream>
#include <stack>
#include <optional>
#include <functional>
#include <chrono>
#include <list>
#include <variant>
#include <charconv>
#include <float.h>
#include <cassert>

#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
#include "stb_image.h"
#include "typedefs.h"
#include "utils.h"
#include "iterator.h"
#include "math.h"
#include "fixed_size_string.h"
#include "buffer.h"
#include "shader.h"
#include "light.h"
#include "texture.h"
#include "material.h"
#include "mesh.h"
#include "window.h"
#include "sprite_batch.h"
#include "geo_batch.h"
#include "text_batch.h"
#include "save.h"
#include "menu.h"
#include "gui.h"
#include "animator.h"
#include "state_machine.h"
#include "common.h"
#include "particle_sys.h"
#endif